### PR TITLE
Dependencies in dbw_node and twist_controller fixed. It drives!

### PR DESCRIPTION
**Pull request by Shtaiven**

### CODE REVIEW

**Comment by shanghaijo** [comment]
Fantastic, thanks a lot!! My VM died just before I could try it (no hard drive space, wrecked it havoc!!). I am looking forward to trying it

**Comment by Shtaiven** [comment]
@shanghaijo try giving your VM a fixed size if you decide to reinstall! it might take up more space now but will save you a huge headache later. 25gb is generally considered a good size for a minimal linux install

**Comment by Shtaiven** [comment]
Already had done so on a separate branch. The walkthrough code from part 3 and 4 doesn't work as-is so i've been trying to work on it in the tl_detector branch.

**Comment by shanghaijo** [comment]
yes, I am sure it doesn't and just provide a base to save some time.

**Comment by shanghaijo** [comment]
Let me know what you need me to do then so we are aligned ;-)

**Comment by Shtaiven** [comment]
I'll merge your work into mine so we can be working on the same base and you keep your commit in the repo history. Let's implement the fix in the tl_detector branch

**Pull request merged**
